### PR TITLE
Update NTP servers and adjust check-in to start earlier

### PR DESCRIPTION
**Pull request by dmytrokoren**

### CODE REVIEW

**Comment by dmytrokoren** [comment]
@jdholtz, I found some older logs from a month ago and noticed that the code was set to start 5 seconds early. However, the logs show that a successful attempt was made on the 5th try, meaning the first 4 attempts failed with a 0.5-second sleep time between each, totaling 2 seconds. To avoid the "429" error (check-in not available yet), I've adjusted the early start to 3 seconds instead of 5. I have a check-in soon and will be testing this change.

Additionally, I read on some forums that Southwest uses time synchronization from time.gov. Therefore, I set the primary server to time.nist.gov and the backup server to pool.ntp.org

**Comment by jdholtz** [comment]
> To avoid the "429" error (check-in not available yet), I've adjusted the early start to 3 seconds instead of 5

Isn’t the 'check-in not available yet' error a 400 Bad Request? That’s what I believe you get during those first few seconds that it tries to check-in early.

I also have removed the 5 seconds before check-in time in the develop branch. There’s been a few check-ins I’ve tried it on and it seems to work the exact same, if not faster (I get less 400, check-in not available yet errors).

**Comment by dmytrokoren** [comment]
> I recommend leaving time.cloudflare.com as the main server. It has the best latency.

I'll use cloudflare as backup server

**Review by jdholtz — APPROVED** [review]

**Comment by jdholtz** [comment]
> Additionally, I read on some forums that Southwest uses time synchronization from time.gov. Therefore, I set the primary server to time.nist.gov and the backup server to pool.ntp.org

Could you link to a forum where this is mentioned (not in the code, just in a comment on this PR) Just for reference purposes.

**Comment by dmytrokoren** [comment]
> > Additionally, I read on some forums that Southwest uses time synchronization from time.gov. Therefore, I set the primary server to time.nist.gov and the backup server to pool.ntp.org
> 
> Could you link to a forum where this is mentioned (not in the code, just in a comment on this PR) Just for reference purposes.

its not a direct answer, but as mentioned by one Reddit user - https://www.reddit.com/r/SouthwestAirlines/comments/hbo6sx/comment/fvcbnbx/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by jdholtz** [comment]
Thanks @dmytrokoren!

**Pull request merged**
