### PR TITLE
Adding devcontainer.json

### PR DESCRIPTION
**Pull request by ankit-jha**
https://github.com/jdholtz/auto-southwest-check-in/issues/239

### CODE REVIEW

**Comment by jdholtz** [comment]
Thanks for the PR! I did not know about GitHub Codespaces before this, but this looks really cool! Definitely can add this to the project.

I have a few suggestions for the container config. First, it appears that `postCreateCommand` can be a list of strings ([reference](https://containers.dev/implementors/spec/#devcontainerjson)). Can that command be split up into two strings--one for installing Chrome and the other for installing the requirements. It makes more logical sense than chaining all of them, as they aren't related.

Also, the dev requirements should also be downloaded with pip --> `pip install -r requirements.txt -r tests/requirements.txt`.

Is there any reason for the `postStartCommand` or can it be removed? 

Just a minor style issue too, the newline (shows up as a red circle in the diff) should be removed. If you configure your editor to use the `.editorconfig`, it should remove it when you save the file.

**Comment by ankit-jha** [comment]
**PR Updated**
I tried the below configuration but couldn't seem to get it working
```json 
     "postCreateCommand": [
         "sudo apt-get update -y",
         "wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb",
         "sudo apt install ./google-chrome-stable_current_amd64.deb -y"
     ]
```
So, I put all the commands in  a script and that seemed to work 

I added the `postStartCommand` as a success check. I think a better alternative would be running all tests at the start.
Also, I updated the style as per `.editorconfig`

**Comment by jdholtz** [comment]
For the `postCreateCommand`, I meant something more like this, so related commands are still chained together:
```json
     "postCreateCommand": [
         "sudo apt-get update -y && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && sudo apt install ./google-chrome-stable_current_amd64.deb -y",
         "pip install -r requirements.txt -r tests/requirements.txt" 
     ]
```
but if that doesn't work, you can just chain them together how they were before. I'd rather have that than a separate file.

Also, the `containerEnv` configuration doesn't have any affect because the environment variable is actually `AUTO_SOUTHWEST_CHECK_IN_BROWSER_PATH`, but `/usr/bin/google-chrome` is already a path the script looks at so it shouldn't be necessary.

> I think a better alternative would be running all tests at the start.

I think it is good for now. It can always be updated later (not in this PR) if that seems beneficial.

**Comment by ankit-jha** [comment]
> For the `postCreateCommand`, I meant something more like this, so related commands are still chained together:
> 
> ```json
>      "postCreateCommand": [
>          "sudo apt-get update -y && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && sudo apt install ./google-chrome-stable_current_amd64.deb -y",
>          "pip install -r requirements.txt -r tests/requirements.txt" 
>      ]
> ```
> 
> but if that doesn't work, you can just chain them together how they were before. I'd rather have that than a separate file.
> 
> Also, the `containerEnv` configuration doesn't have any affect because the environment variable is actually `AUTO_SOUTHWEST_CHECK_IN_BROWSER_PATH`, but `/usr/bin/google-chrome` is already a path the script looks at so it shouldn't be necessary.
> 
> > I think a better alternative would be running all tests at the start.
> 
> I think it is good for now. It can always be updated later (not in this PR) if that seems beneficial.

I tried again but it just doesn't chain the commands correctly. I will keep trying but for now I made the asked changes.

**Comment by jdholtz** [comment]
> I tried again but it just doesn't chain the commands correctly. I will keep trying but for now I made the asked changes.

It’s likely the specification on the website I linked to is wrong and doesn’t allow an array. Thanks for the PR and making the corresponding changes!

**Pull request merged**
