### PR TITLE
Add fare checker for scheduled flights

### LINKED ISSUE #38: Fare Check
I am not sure if this is possible, but it would be pretty cool if you could add the fare you paid and have the system check if the fare went down for the same flight.

Since the system knows the flights and confirmation code...maybe use a script like

Southwest.py CONFIRMATION $/POINTS XXXXX

So, you'd be telling the system to attribute either dollars or points to the flights/confirmation.  If the flight drops in cost a notification is sent.

### PR DESCRIPTION
**Pull request by jdholtz**
Fixes #38.

Every 24 hours (or the `retrieval_interval` set by the user), the script will check if there are any scheduled flights that have lower fares. 

It is disabled by default for right now. However, I plan to enable by default once it is more thoroughly tested. If you decide to use this, please give me feedback on how it works in this PR or in issue #38.

To enable it, put `"check_fares": true` in your `config.json`. If you want to see it working in more detail, you can use the `--verbose` flag (by default, nothing will be printed if there aren't lower fares).

The first two commits of this PR were attached by mistake.

### CODE REVIEW

**Comment by ctkubik** [comment]
This is awesome.  I have a few flights I need to check into this week, so I want to stay on 3.1 for that.  Would you suggest creating a new container (on the same machine) to run this build?  Would it create a conflict trying to check me in to the same flight?  If so, I may wait until I am back home next week to give this a shot.  CHEERS!!!!

**Comment by jdholtz** [comment]
> Would you suggest creating a new container (on the same machine) to run this build?

Since this is still on the `fare_checker` branch, there isn't a Docker image available that has this feature yet. However, you can easily build the Docker image yourself which would allow you to run a container with this feature. 

> Would it create a conflict trying to check me in to the same flight?

It should not. If the fare checker fails, the error will be caught and it will not affect the check-in process (however, unexpected errors are not caught).

**Comment by ctkubik** [comment]
Awesome.  Thank you!  I'm an extreme novice when it comes to Docker....I have a lot of learning to do there (I need longer days).  I appreciate your hard work.  The first fare I get some money back I'm going to send it to you.

**Comment by babehboi** [comment]
Ooh! I can't wait to give this a try when I get home!

**Comment by fusionneo** [comment]
I've been doing some testing and I've found a few issues. 

1) The `safe_sleep` method in `checkin_handler.py` seems to prevent flight fares from being checked. I had to comment out the safe_sleep call in `_wait_for_check_in` (as well as comment out the `self._check_in()` to prevent it from spamming check in) to get it to start searching for flight prices.

2) The fare checker does not work if you have added your companion from your companion pass. This is because Southwest does not allow you to change the flight if you have a companion added. You must first cancel your companion's ticket before making any changes. So `fare_checker.py` crashes on this line: `info = response["viewReservationViewPage"]["_links"]["change"]` because the change link is `null`. 

2a) Companion pass support in general I think is missing from the application. Companions have a separate ticket/separate reservation so I don't think auto check in functionality would work for your companion since they are not listed on the same reservation as you.

Hope this helps.

**Comment by jdholtz** [comment]
Thanks for testing this @fusionneo. 

1. What OS are you running? I haven't tested this on Windows, but the check-ins are done in a separate Process as the flight fare check so they shouldn't have any effect on the other's execution. 
2. This is good to know. I will add a fix for this before merging

> Hope this helps and that I'm not coming off negative

Not at all. This is exactly why I want to open this feature up to users before finalizing it (an alpha/beta stage). I'm not able to test every scenario of Southwest reservations, so comments like these are really helpful in improving the reliability of the script.

**Comment by fusionneo** [comment]
1) I'm running Windows 11. That said, I think my initial debugging was mistaken. I canceled my companion's ticket and it was able to start checking fare prices (or at least attempting to, I'm getting 429 issues when checking) and when I added my companion again the issue returned.

**Comment by ctkubik** [comment]
@fusionneo I was having similar issues with Windows 11 after a Chrome update.  I installed Docker and those issues seem to have gone away. I'm a total noob with Docker, but it is pretty easy.

**Comment by fusionneo** [comment]
I can confirm the issue only appears to happen if a companion is attached to the ticket. Without a companion, everything works fine. I'm setting up Docker to see if the issue persists there with a companion attached.

Posting now because I did find another issue. Right now, fare checker only checks if the Wanna Get Away fare price is lower than what you paid. So if you book a Wanna Get Away Plus, Anytime, or Business Select Ticket, fare_checker will erroneously report a lower fare found because the Wanna Get Away price is lower than the other fare classes.

**Comment by jdholtz** [comment]
Good catch @fusionneo. Thanks for posting code that could potentially fix this. That seems like a good way to go. 

> I'm unsure if bounds will always only have one item in the list

For round-trip flights, there are two items (one outbound and one inbound).

**Comment by jdholtz** [comment]
> Right now, fare checker only checks if the Wanna Get Away fare price is lower than what you paid

Currently, the fare checker gets the `startingFromPriceDifference` attribute of the flight that is on the page. Does that attribute only hold the WGA fare? I would assume it holds whichever fare type matches the current flight, but I can't say for sure (and maybe you have evidence of the contrary).

**Comment by fusionneo** [comment]
> > Right now, fare checker only checks if the Wanna Get Away fare price is lower than what you paid
> 
> Currently, the fare checker gets the `startingFromPriceDifference` attribute of the flight that is on the page. Does that attribute only hold the WGA fare? I would assume it holds whichever fare type matches the current flight, but I can't say for sure (and maybe you have evidence of the contrary).

Correct, it holds the WGA fare - counterintuitive based on the naming.

In my case, I have two upcoming flights I'm monitoring that I booked WGA+ fares for. After getting the fare_checker set up it immediately notified me of a lower fare but when I checked it was just the difference between WGA+ and WGA. After implementing my changes it seems to correctly be tracking for price changes.

**Comment by fusionneo** [comment]
Just reporting back that the changes I made above did work and I was able to find a lower fare for my flight today in the same fare type (lower fare correctly reported and notified for WGA+ to WGA+)

I will note that I noticed that it would occasionally get stuck here:

```
2023-04-19 13:29:31 DEBUG Process-1[webdriver]: Logging into Southwest account to get scheduled flights and valid headers
2023-04-19 13:29:43 DEBUG Process-1[webdriver]: Setting valid headers from previous request
```

I was able to debug and it was because apparently the 10 second sleep in the `_set_headers_from_request` method in `webdriver.py` was not always long enough. If it took longer than 10 seconds to log in, for whatever reason, it would get stuck here.

I've tweaked `webdriver.py` a little bit and it seems to be more reliable.

```
def get_flights(self, flight_retriever: AccountFlightRetriever) -> Dict[str, Any]:
        """
        Logs into the flight retriever account to retrieve a list of scheduled flights.
        Since valid headers are produced, they are also grabbed and updated in the check-in
        scheduler. Last, if the account name is not set, it will set it based on the response
        information.
        """
        driver = self._get_driver()
        logger.debug("Logging into Southwest account to get scheduled flights and valid headers")

        # Log in to retrieve the account's trips and needed headers for later requests
        WebDriverWait(driver, 30).until(EC.invisibility_of_element((By.CLASS_NAME, "dimmer")))
        WebDriverWait(driver, 30).until(
            EC.element_to_be_clickable((By.CLASS_NAME, "login-button--box"))
        ).click()

        username_element = WebDriverWait(driver, 30).until(
            EC.presence_of_element_located((By.NAME, "userNameOrAccountNumber"))
        )
        username_element.send_keys(flight_retriever.username)

        password_element = WebDriverWait(driver, 30).until(
            EC.presence_of_element_located((By.NAME, "password"))
        )
        password_element.send_keys(flight_retriever.password)
        password_element.submit()
        
        while driver.requests == []:
            time.sleep(0.5)
            
        while driver.requests[0].response == None:
            time.sleep(0.5)
        
        response = driver.requests[0].response
        if response.status_code != 200:
            driver.quit()
            error = self._handle_login_error(response)
            raise error
                            
        self._set_headers_from_request(driver)

        # If this is the first time logging in, the account name needs to be set
        # because that info is needed later
        if flight_retriever.first_name is None:
            logger.debug("First time logging in. Setting account name")
            response_body = json.loads(response.body)
            self._set_account_name(flight_retriever, response_body)
            print(
                f"Successfully logged in to {flight_retriever.first_name} "
                f"{flight_retriever.last_name}'s account\n"
            )  # Don't log as it contains sensitive information

        # This page is also loaded when we log in, so we might as well grab it instead of
        # requesting again later
        
        flights = json.loads(driver.requests[1].response.body)["upcomingTripsPage"]

        driver.quit()

        return [flight for flight in flights if flight["tripType"] == "FLIGHT"]
```

Here, I changed it to wait for there to be a driver.request before trying to check the response, and then waiting for a response before trying to check the status code. This way, we can capture any login errors before trying to set the headers, and it also was faster than waiting the hard coded 10 seconds in the `_set_headers_from_request` method. Then `_set_headers_from_request` has also been tweaked slightly.

```
    def _set_headers_from_request(self, driver: Chrome) -> None:
        # Retrieving the headers could fail if the form isn't given enough time to submit
       WebDriverWait(driver, 60).until(
        EC.element_to_be_clickable((By.CSS_SELECTOR, """#appContents > div.check-in > 
                                    div > div.reservation-retrieval-form > div > 
                                    form > fieldset > div > div.segment > button"""))
        )
        
        time.sleep(1)
        logger.debug("Setting valid headers from previous request")
        request_headers = driver.requests[0].headers
        self.checkin_scheduler.headers = self._get_needed_headers(request_headers)
```

Instead of a hardcoded 10 second sleep, I changed it to wait _up to_ 60 seconds for the yellow button to appear after signing in. Usually, it's already on the page. Once it appears, we wait one additional second just to make sure all the headers we need are there, then we get them as normal.

I also made a minor change by logging a 429 error I was getting when trying to debug. 

In my testing, these changes have sped up the login process as well as made it more reliable. I've been running it for 5 hours now with a refresh interval of every hour and it has not crashed (previously, it would crash every 2-4 hours.)

If you want me to submit a pull request, let me know.

**Comment by jdholtz** [comment]
Great to hear. I will implement those changes this weekend (unless I have more time this week). For the webdriver fixes, could we move this to a GitHub Discussion as it doesn't really pertain to the fare checker? And yes, it would be great if you want to submit a pull request.

**Comment by jdholtz** [comment]
Hey @fusionneo. There is a slight issue with the new fare check strategy. Sometimes, the fare might not exist anymore (I had this happen before the second flight of a round-trip reservation). 

I'll fix this by defaulting to display the information that was retrieved before this change was made. I don't think a false alarm will be triggered in this case because Southwest probably doesn't have lower fares available whilst having higher fares unavailable (although I am not 100% sure on this).

**Comment by fusionneo** [comment]
> Southwest probably doesn't have lower fares available whilst having higher fares unavailable (although I am not 100% sure on this).

This would be theoretically possible. If someone books a Business Select fare, there are only 15 of those fares available. Once all 15 tickets are sold, that fare is no longer available, but WGA tickets could still be available which would be substantially cheaper.

Is it possible where if the fare doesn't exist anymore, it gets returned as a zero price difference?

**Comment by jdholtz** [comment]
Gotcha. 

> Is it possible where if the fare doesn't exist anymore, it gets returned as a zero price difference?

Yes, that will be the best way to do it now.

**Comment by jdholtz** [comment]
First off, thanks for fixing multiple issues @fusionneo. Also, thanks for testing @babehboi.

I have tested on multiple round-trip flights and one-way flights. Additionally, @fusionneo has tested with companion passes and different fare types. As there are no more known issues currently, I will merge this and it will be a part of v4.0. It will still be off by default as I want to make sure all of the different issues are brought to light before enabling it by default.

**Comment by thuss** [comment]
Thank you so much for this feature! I had no idea it was part of the program, but it just notified me and I got a lower fare, amazing.

**Pull request merged**
