### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by aneisch**
Add Dockerfile so this can be run more easily in a self-contained environment.

### CODE REVIEW

**Comment by jdholtz** [comment]
Thanks for the PR! I've tested it out and it seems to work for the most part. Have you tried this on an actual flight yet? I don't want to merge this until I know it works with a flight in real-time.

I have a few fixes/suggestions:

1. You don't need to actually install the chromedriver in the Docker container, as undetected-chromedriver downloads and patches it automatically.

2. I was able to get it to successfully log in without having the DISPLAY env variable set. Were you having issues with this?

3. If you add ENTRYPOINT ["python3", "southwest.py"] at the end of the Dockerfile, the command to run the container can be `docker run --name=auto-southwest-check-in auto-southwest-check-in USERNAME PASSWORD`. You would just be able to append the script arguments to the end which, personally, makes it a lot easier to run.

Also, I'll try to switch this to merge with the master branch instead as I don't want this to be deleted if I merge the notifications branch.

I'll also add a commit to this to add an argument to the chromedriver which fixes it running in Docker.

**Comment by jdholtz** [comment]
Try adding the line `option.add_argument("--disable-dev-shm-usage")` on line 99 in lib/webdriver.py. Chrome wasn't working correctly without this flag because it ran on limited resources. I was able to successfully log in when I used this flag during testing.

**Comment by austinaoliu** [comment]
I tried to build the container using the code but docker complains about executable file not found.

`docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "python3 southwest.py USERNAME PASSWORD": executable file not found in $PATH: unknow`

Which OS are you using?

**Comment by austinaoliu** [comment]
> 1. You don't need to actually install the chromedriver in the Docker container, as undetected-chromedriver downloads and patches it automatically.

I tried to remove `undetected_chromedriver==3.1.5r4` from the requirements, but the container would complain about that
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 6, in <module>
    import undetected_chromedriver as uc
ModuleNotFoundError: No module named 'undetected_chromedriver'

The above exception was the direct cause of the following exception:

```
Traceback (most recent call last):
  File "/usr/src/app/southwest.py", line 4, in <module>
    from lib.account import Account
  File "/usr/src/app/lib/account.py", line 7, in <module>
    from .webdriver import WebDriver
  File "/usr/src/app/lib/webdriver.py", line 10, in <module>
    from seleniumwire.undetected_chromedriver import Chrome, ChromeOptions
  File "/usr/local/lib/python3.10/site-packages/seleniumwire/undetected_chromedriver/__init__.py", line 1, in <module>
    from .webdriver import Chrome, ChromeOptions
  File "/usr/local/lib/python3.10/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 8, in <module>
    raise ImportError(
ImportError: undetected_chromedriver not found. Install it with `pip install undetected_chromedriver`.
```

**Comment by jdholtz** [comment]
> I tried to remove undetected_chromedriver==3.1.5r4 from the requirements, but the container would complain about that

I meant that you could remove explicitly installing the chromedriver in the docker container. You still need to install the undetected_chromedriver package as that is what installs the chromedriver automatically.

**Comment by jdholtz** [comment]
@aneisch Do you still want to work on this PR?

**Pull request closed without merging**
