### PR TITLE
Update dockerfile to respect chrome_version

### PR DESCRIPTION
**Pull request by everettsouthwick**
This pull request adds a script that will pull from the Google Version History API and respect the major Google Chrome version specified in config.json in the docker configuration

### CODE REVIEW

**Comment by everettsouthwick** [comment]
@jdholtz I was curious if you had already tried to base your dockerfile on alpine instead of ubuntu to reduce the file size? If you had already made an attempt at it and it didn't work, I don't want to start down a path already ventured. If not, I can look into seeing if I can make alpine the base image to reduce the size.

**Comment by jdholtz** [comment]
Thanks for the PR @everettsouthwick! However, I'm not sure if it is necessary to use the same chrome_version as specified in the config.json since Chrome will still need to be downloaded in the container (unlike if the user wanted to use an already installed version if they ran the script on their system).

This will also present a problem when I add this image to the public repository (see #49). Since the image will already be built, this script wouldn't actually run.

This does hint to a better way of getting the Chrome version within the Docker container though. Currently, I have users just find the latest stable version that the Docker container will download and put that into their `config.json` before building the container. However, adding it to the public repository will make users unaware of what Chrome version actually exists in that image. 

The best approach, I think, would be to set an environment variable `CHROME_VERSION` after installing chrome that gets the major version of chrome installed (possibly like this: `ENV CHROME_VERSION=$(google-chrome-stable --version | awk -F '[ .]' '{print $3}')` -- however the syntax is in the Dockerfile). Then, [this](https://github.com/jdholtz/auto-southwest-check-in/blob/026c7fcbc64ed0f483eb90e0cdbc3f21c835076f/lib/config.py#L18) line can be changed to `os.getenv("CHROME_VERSION", None)`.

> I was curious if you had already tried to base your dockerfile on alpine instead of ubuntu to reduce the file size?

I did try and I was not able to get google-chrome to install (there is no package for it) and chromium is outdated (it can be built from source though). Feel free to try though!

**Comment by everettsouthwick** [comment]
> Thanks for the PR @everettsouthwick! However, I'm not sure if it is necessary to use the same chrome_version as specified in the config.json since Chrome will still need to be downloaded in the container (unlike if the user wanted to use an already installed version if they ran the script on their system).
> 
> This will also present a problem when I add this image to the public repository (see #49). Since the image will already be built, this script wouldn't actually run.
> 
> This does hint to a better way of getting the Chrome version within the Docker container though. Currently, I have users just find the latest stable version that the Docker container will download and put that into their `config.json` before building the container. However, adding it to the public repository will make users unaware of what Chrome version actually exists in that image.
> 
> The best approach, I think, would be to set an environment variable `CHROME_VERSION` after installing chrome that gets the major version of chrome installed (possibly like this: `ENV CHROME_VERSION=$(google-chrome-stable --version | awk -F '[ .]' '{print $3}')` -- however the syntax is in the Dockerfile). Then, [this](https://github.com/jdholtz/auto-southwest-check-in/blob/026c7fcbc64ed0f483eb90e0cdbc3f21c835076f/lib/config.py#L18) line can be changed to `os.getenv("CHROME_VERSION", None)`.
> 
> > I was curious if you had already tried to base your dockerfile on alpine instead of ubuntu to reduce the file size?
> 
> I did try and I was not able to get google-chrome to install (there is no package for it) and chromium is outdated (it can be built from source though). Feel free to try though!

Thank you for the reply, that sounds like a good solution to me. 

I have updated the pull request to include a docker ARG `SET_CHROME_VERSION` you can pass in on the docker build (e.g. `docker build -f Dockerfile . -t auto-southwest-check-in --build-arg SET_CHROME_VERSION=108`) that sets the `CHROME_VERSION` environment variable. By default, if this is not specified, it uses 109. 

I then use that variable to set the version that is installed with `chrome_install.py` as well as what the `config.py` gets if it is available. In addition, I added a conversion of chrome_version to integer in the config if it is not an integer (as the environment passes it as a string), and then raising the error if it does not succeed.

I'll hold off on trying Alpine since it seems like it will be difficult getting Google Chrome to install on there.

**Comment by jdholtz** [comment]
I appreciate the changes. However, my main point in that comment is that, since I will be adding the image to my public repository soon (hopefully this weekend), the image will already be built meaning this script would never actually run. 

My second point is that the `chrome_version` configuration option is meant for users to not have to use the latest version of Chrome on their system all the time. However, in the Docker image, this option isn't necessary as Chrome will need to be downloaded when its built (and therefore the version won't matter because the script *should* always work with the latest Chrome version).

Let me know your thoughts on this.

**Comment by jdholtz** [comment]
As I have added the image to the public repository, the user won't have control over the Google Chrome version already present in the container (because it is already built). I appreciate the effort you put into this PR but I don't see that this change is needed anymore.

**Pull request closed without merging**
