### PR TITLE
fix form-urlencoding for passwords

### PR DESCRIPTION
**Pull request by davidkassa**
The mobile Southwest site doesn't properly encode their form submission (likely a JS bug). To work around this, we can encode the password value.

Tested with a password containing all the allowed characters except `<` and `>`. They are supposedly allowed, but current desktop UI prohibits them on password update. Used password `A1!@#$%^*();:/\` as a test.

### CODE REVIEW

**Comment by jdholtz** [comment]
Thanks for the fix and updating the Changelog. What was the error you were getting that this solved? An invalid credentials? 

If it is a problem with Southwest’s form submission, do you get a problem when using the site too?

**Comment by davidkassa** [comment]
Yes, the error is for invalid credentials and, yes, manually navigating to the site and sending a non-encoded password fails and an encoded one works. (The desktop and native App work as expected). On Aug 20, 2023, at 12:54 PM, Joey Holtzman ***@***.***> wrote:﻿
Thanks for the fix and updating the Changelog. What was the error you were getting that this solved? An invalid credentials?
If it is a problem with Southwest’s form submission, do you get a problem when using the site too?

**Comment by jdholtz** [comment]
Thats interesting. I’m surprised that’s been an issue they haven’t fixed this entire time. 

The unit tests for the webdriver are failing right now. I believe it’s because the password is never actually set in the tests. You can try to fix the tests, but I always can before merging if you aren’t able to figure it out.

**Comment by davidkassa** [comment]
hmm, they passed locally (on Windows). I'll see if I can make the changes today.

**Comment by jdholtz** [comment]
Tested and it works nicely! Thanks!

**Pull request merged**
