### PR TITLE
Containerization

### LINKED ISSUE #18: Adding a Docker container to run in the background?
This could be a nice feature to add in the future... It also avoids issues with dependencies across different systems as everything is standardized under the container.

### PR DESCRIPTION
**Pull request by sdstolworthy**
Closes #18

### CODE REVIEW

**Comment by sdstolworthy** [comment]
`entrypoint.sh` tests which env vars are defined. It runs the application in "account" mode or "reservation" mode depending on what is provided. @jdholtz it might be worth considering at some point supporting similar environment variables more generally in the application.

I used `ubuntu:latest` as the base image. Reading through #17, it seems that there may be some issues running on specific versions of Ubuntu. If you have any guidance on that, I'd love to hear it. I chose Ubuntu because it was no hassle to install Chrome on it, but if there's another route you'd prefer, again, all ears.

**Comment by adyotag** [comment]
Thanks for taking the initiative; it looks good - I just have to run it on my end to see :-)

**Comment by sdstolworthy** [comment]
@jdholtz Perfect. I'm good either way. If you've already made the changes, it may be easier just to have you merge into my branch?

**Comment by sdstolworthy** [comment]
I just sent you an invite to my fork.

**Comment by jdholtz** [comment]
Thanks. I'll commit those changes now.

**Comment by jdholtz** [comment]
What I'll do for now is remove `entrypoint.sh` in favor of adding ENV variable support directly in the script. Until I add that though, I'll make it so you the arguments passed in at the end of the `docker run` command will be passed to the script. 
Ex: `docker run -d auto-southwest-check-in USERNAME PASSWORD`

**Comment by jdholtz** [comment]
Thanks @sdstolworthy. You can remove push access in your fork now (if you want).

**Comment by jdholtz** [comment]
Hey @sdstolworthy. I added the ability to specify accounts and flights in the configuration file in #33. Is this a sufficient alternative to supporting environment variables, per your use case?

**Pull request merged**
