### PR TITLE
Minor updates to WebDriver file

### PR DESCRIPTION
**Pull request by dmytrokoren**
- Set driver option "mobile=True"
- Go to check-in page directly instead of homepage

### CODE REVIEW

**Review by dmytrokoren — COMMENTED** [review]
@jdholtz please review

**Comment by jdholtz** [comment]
@dmytrokoren are these changes to help avoid 403/429s?

I’ve been super busy so I haven’t been able to maintain this very actively. Hopefully I’ll have a bit more time after this weekend.

**Comment by dmytrokoren** [comment]
> @dmytrokoren are these changes to help avoid 403/429s?
> 
> I’ve been super busy so I haven’t been able to maintain this very actively. Hopefully I’ll have a bit more time after this weekend.

Yes this is to help void 429/403 but with SW its not 100% possible.

**Comment by jdholtz** [comment]
Thanks @dmytrokoren!

**Pull request merged**
